### ISSUE TITLE
持仓数据 - 获取出错

### ISSUE THREAD

**Issue by Yaolinwang** [LowinLi/fushare#13]
![image](https://user-images.githubusercontent.com/26902034/51806179-ba495780-2244-11e9-8f7c-a9c4b0a6bf25.png)

如果没有数据或者不available的话，最好能返回个NAN之类的

**Comment by LowinLi** [comment]
朋友，请改成
`f.get_reciept(start = '20150101', end = '20150125', vars = ['TA'])`

**Comment by Yaolinwang** [comment]
sorry, 没有仔细看输入要求。换成list之后可以了。谢谢及时回复！
