### ISSUE TITLE
api无法在终端命令行中运行（无法以脚本形式执行）

### ISSUE THREAD

**Issue by fasterpython** [LowinLi/fushare#3]
现在是只能在Jupyter Notebook中运行吗？
在console command line运行时，依赖一些画图的组件，会导致报错。
比方说这个错误：
no module named '_tkinter'， 
只从fushare api提取数据，不画图，是否可以尽量减少依赖？ 特别是不要依赖tkinter，这个比较不友好。

**Comment by LowinLi** [comment]
其实调用展期收益率时候，plot这个参数就是可以选True或False来决定是否画图。
但是另一个问题是，如果不画图，但是在脚本里导入画图的库，是不是也不太友好呢?
fushare.get_rollYield_bar(type = 'date', var = 'RB', start = '20180618', end = '20180718',**plot = True**)
