### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by A-DetyY** [LowinLi/fushare#7]
symbolVar.py 中 chinese_to_english 函数 ‘纸浆’ 和对应的 ‘SP' 后面都没有逗号，应该要加的吧

**Comment by LowinLi** [comment]
> symbolVar.py 中 chinese_to_english 函数 ‘纸浆’ 和对应的 ‘SP' 后面都没有逗号，应该要加的吧

谢谢提示，我已经在PYPI的1.1.19版本打包好了，github上更新太慢，Pycharm上传更新项目老有问题。建议用PYPI更新为准。
